<a href="https://colab.research.google.com/github/maxy808/CLIP_video/blob/frame-selection-xiaoyang/CLIP_video_0_1_frame2%2BseqTransf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/sijiasiga/CLIP_video
%cd CLIP_video

Cloning into 'CLIP_video'...
remote: Enumerating objects: 230, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 230 (delta 29), reused 0 (delta 0), pack-reused 187 (from 1)
Receiving objects: 100% (230/230), 1.51 MiB | 10.15 MiB/s, done.
Resolving deltas: 100% (128/128), done.
/content/CLIP_video

In [2]:
# From CLIP
!conda install --yes -c pytorch pytorch=1.7.1 torchvision cudatoolkit=11.0
!pip install ftfy regex tqdm
!pip install opencv-python boto3 requests pandas

/bin/bash: line 1: conda: command not found
Collecting ftfy
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from ftfy) (0.2.13)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.8 MB/s eta 0:00:00
Installing collected packages: ftfy
Successfully installed ftfy-6.3.1
Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (4.11.0.86)
Collecting boto3
  Downloading boto3-1.38.3-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.11/dist-packages (from opencv-python) (2.0.2)
Collecting botocore<1.39.0,>=1.38.3 (from boto3)
  Downloading botocore-1.38.3-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.13.0,>=0.12.0 (from boto3)
  Downloading s3transfer-0.12.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading boto3-1.38.3-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 3.2 MB/s eta 0:00:00
Downloading botocore-1.38.3-py3-none-any.whl (13.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 113.4 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.12.0-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 8.6 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.38.3 botocore-1.38.3 jmespath-1.0.1 s3transfer-0.12.0

In [3]:
# Connet to google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# # Comment if the file exits
# !wget -O /content/drive/MyDrive/Data/msrvtt_data.zip https://github.com/ArrowLuo/CLIP4Clip/releases/download/v0.0/msrvtt_data.zip
# !unzip /content/drive/MyDrive/Data/msrvtt_data.zip -d /content/drive/MyDrive/Data/

In [4]:
DATA_PATH = "/content/drive/MyDrive/Data/msrvtt_data"  # Directory of MSRVTT data
VIDEO_PATH = "/content/drive/MyDrive/Data/video"    # Directory of MSRVTT raw video

In [7]:
# import pandas as pd

# # Load training dataset
# train_path = f"{DATA_PATH}/MSRVTT_train.9k.csv"
# df = pd.read_csv(train_path)

# print("Size: ", len(df))
# print("Column names", df.columns.tolist())
# display(df.head())

# # Choose a subset
# def sample_subset(df, frac=0.1, random_state=42):
#     return df.sample(frac=frac, random_state=random_state).reset_index(drop=True)

# # Set fraction to 0.1
# subset_df = sample_subset(df, frac=0.1)
# print("Size of subset：", len(subset_df))
# display(subset_df.head())

Size:  9000
Column names ['video_id']

  video_id
0   video0
1   video1
2   video2
3   video3
4   video4

Size of subset： 900

    video_id
0  video8405
1  video1162
2   video582
3  video4081
4  video9139

In [8]:
# # Save the subset
# subset_path = f"{DATA_PATH}/MSRVTT_train.subset.csv"
# subset_df.to_csv(subset_path, index=False)

# print("Subset CSV saved to:", subset_path)

Subset CSV saved to: /content/drive/MyDrive/Data/msrvtt_data/MSRVTT_train.subset.csv

In [5]:
import torch
print("Current device:", torch.cuda.get_device_name() if torch.cuda.is_available() else "CPU only")

Current device: NVIDIA A100-SXM4-40GB

In [6]:
!wget -P ./modules https://openaipublic.azureedge.net/clip/models/40d365715913c9da98579312b702a82c18be219cc2a73407c4526f58eba950af/ViT-B-32.pt

--2025-04-28 03:11:26--  https://openaipublic.azureedge.net/clip/models/40d365715913c9da98579312b702a82c18be219cc2a73407c4526f58eba950af/ViT-B-32.pt
Resolving openaipublic.azureedge.net (openaipublic.azureedge.net)... 13.107.246.38, 2620:1ec:bdf::38
Connecting to openaipublic.azureedge.net (openaipublic.azureedge.net)|13.107.246.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 353976522 (338M) [application/octet-stream]
Saving to: ‘./modules/ViT-B-32.pt’

ViT-B-32.pt         100%[===================>] 337.58M  63.8MB/s    in 5.9s

2025-04-28 03:11:32 (57.0 MB/s) - ‘./modules/ViT-B-32.pt’ saved [353976522/353976522]

In [7]:
torch.cuda.empty_cache()

In [9]:
# Updata changes to files. Comment if the files are not changed
!cd CLIP_video && git pull

/bin/bash: line 1: cd: CLIP_video: No such file or directory

In [10]:
# !pip install ffmpeg
# !python /content/CLIP_video/preprocess/compress_video.py --input_root "/content/drive/MyDrive/IDL/IDL Project/Data/video" --output_root "/content/drive/MyDrive/IDL/IDL Project/Data/compressed_video"

Collecting ffmpeg
  Downloading ffmpeg-1.4.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ffmpeg
  Building wheel for ffmpeg (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6083 sha256=7d3af04e3806d03133b68c2049514b40c6a960adfaaeccb1a6171b7ec7ea26a1
  Stored in directory: /root/.cache/pip/wheels/56/30/c5/576bdd729f3bc062d62a551be7fefd6ed2f761901568171e4e
Successfully built ffmpeg
Installing collected packages: ffmpeg
Successfully installed ffmpeg-1.4
Total video need to process: 0
Begin with 12-core logical processor.
Compress finished, wait for checking files...

In [8]:
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

!python /content/CLIP_video/main_task_retrieval.py \
  --do_train \
  --num_thread_reader 8 \
  --epochs 20 \
  --batch_size 64 \
  --train_csv  "$DATA_PATH"/MSRVTT_train.subset.csv \
  --val_csv    "$DATA_PATH"/MSRVTT_JSFUSION_test.csv \
  --data_path  "$DATA_PATH"/MSRVTT_data.json \
  --features_path "$VIDEO_PATH" \
  --output_dir /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType \
  --lr 1e-4 \
  --max_words 32 \
  --max_frames 8 \
  --batch_size_val 8 \
  --datatype msrvtt \
  --expand_msrvtt_sentences \
  --feature_framerate 1 \
  --coef_lr 1e-3 \
  --freeze_layer_num 6 \
  --slice_framepos 2 \
  --loose_type \
  --linear_patch 2d \
  --sim_header seqTransf \
  --pretrained_clip_name ViT-B/32 \
  --fp16 \
  --fp16_opt_level O1

04/28/2025 03:21:43 - INFO -   Effective parameters:
04/28/2025 03:21:43 - INFO -     <<< batch_size: 64
04/28/2025 03:21:43 - INFO -     <<< batch_size_val: 8
04/28/2025 03:21:43 - INFO -     <<< cache_dir:
04/28/2025 03:21:43 - INFO -     <<< coef_lr: 0.001
04/28/2025 03:21:43 - INFO -     <<< cross_model: cross-base
04/28/2025 03:21:43 - INFO -     <<< cross_num_hidden_layers: 4
04/28/2025 03:21:43 - INFO -     <<< data_path: /content/drive/MyDrive/Data/msrvtt_data/MSRVTT_data.json
04/28/2025 03:21:43 - INFO -     <<< datatype: msrvtt
04/28/2025 03:21:43 - INFO -     <<< do_eval: False
04/28/2025 03:21:43 - INFO -     <<< do_lower_case: False
04/28/2025 03:21:43 - INFO -     <<< do_pretrain: False
04/28/2025 03:21:43 - INFO -     <<< do_train: True
04/28/2025 03:21:43 - INFO -     <<< epochs: 20
04/28/2025 03:21:43 - INFO -     <<< eval_frame_order: 0
04/28/2025 03:21:43 - INFO -     <<< expand_msrvtt_sentences: True
04/28/2025 03:21:43 - INFO -     <<< feature_framerate: 1
04/28/2025 03:21:43 - INFO -     <<< features_path: /content/drive/MyDrive/Data/video
04/28/2025 03:21:43 - INFO -     <<< fp16: True
04/28/2025 03:21:43 - INFO -     <<< fp16_opt_level: O1
04/28/2025 03:21:43 - INFO -     <<< freeze_layer_num: 6
04/28/2025 03:21:43 - INFO -     <<< gradient_accumulation_steps: 1
04/28/2025 03:21:43 - INFO -     <<< hard_negative_rate: 0.5
04/28/2025 03:21:43 - INFO -     <<< init_model: None
04/28/2025 03:21:43 - INFO -     <<< linear_patch: 2d
04/28/2025 03:21:43 - INFO -     <<< loose_type: True
04/28/2025 03:21:43 - INFO -     <<< lr: 0.0001
04/28/2025 03:21:43 - INFO -     <<< lr_decay: 0.9
04/28/2025 03:21:43 - INFO -     <<< margin: 0.1
04/28/2025 03:21:43 - INFO -     <<< max_frames: 8
04/28/2025 03:21:43 - INFO -     <<< max_words: 32
04/28/2025 03:21:43 - INFO -     <<< n_display: 100
04/28/2025 03:21:43 - INFO -     <<< n_gpu: 1
04/28/2025 03:21:43 - INFO -     <<< n_pair: 1
04/28/2025 03:21:43 - INFO -     <<< negative_weighting: 1
04/28/2025 03:21:43 - INFO -     <<< num_thread_reader: 8
04/28/2025 03:21:43 - INFO -     <<< output_dir: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType
04/28/2025 03:21:43 - INFO -     <<< pretrained_clip_name: ViT-B/32
04/28/2025 03:21:43 - INFO -     <<< rank: 0
04/28/2025 03:21:43 - INFO -     <<< resume_model: None
04/28/2025 03:21:43 - INFO -     <<< sampled_use_mil: False
04/28/2025 03:21:43 - INFO -     <<< seed: 42
04/28/2025 03:21:43 - INFO -     <<< sim_header: seqTransf
04/28/2025 03:21:43 - INFO -     <<< slice_framepos: 2
04/28/2025 03:21:43 - INFO -     <<< task_type: retrieval
04/28/2025 03:21:43 - INFO -     <<< text_num_hidden_layers: 12
04/28/2025 03:21:43 - INFO -     <<< train_csv: /content/drive/MyDrive/Data/msrvtt_data/MSRVTT_train.subset.csv
04/28/2025 03:21:43 - INFO -     <<< train_frame_order: 0
04/28/2025 03:21:43 - INFO -     <<< use_mil: False
04/28/2025 03:21:43 - INFO -     <<< val_csv: /content/drive/MyDrive/Data/msrvtt_data/MSRVTT_JSFUSION_test.csv
04/28/2025 03:21:43 - INFO -     <<< video_dim: 1024
04/28/2025 03:21:43 - INFO -     <<< visual_num_hidden_layers: 12
04/28/2025 03:21:43 - INFO -     <<< warmup_proportion: 0.1
04/28/2025 03:21:43 - INFO -     <<< world_size: 1
04/28/2025 03:21:43 - INFO -   device: cuda n_gpu: 1
04/28/2025 03:21:44 - INFO -   loading archive file /content/CLIP_video/modules/cross-base
04/28/2025 03:21:44 - INFO -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 512,
  "initializer_range": 0.02,
  "intermediate_size": 2048,
  "max_position_embeddings": 128,
  "num_attention_heads": 8,
  "num_hidden_layers": 4,
  "type_vocab_size": 2,
  "vocab_size": 512
}

04/28/2025 03:21:44 - INFO -   Weight doesn't exsits. /content/CLIP_video/modules/cross-base/cross_pytorch_model.bin
04/28/2025 03:21:44 - WARNING -   Stage-One:True, Stage-Two:False
04/28/2025 03:21:44 - WARNING -   Test retrieval by loose type.
04/28/2025 03:21:44 - WARNING -   	 embed_dim: 512
04/28/2025 03:21:44 - WARNING -   	 image_resolution: 224
04/28/2025 03:21:44 - WARNING -   	 vision_layers: 12
04/28/2025 03:21:44 - WARNING -   	 vision_width: 768
04/28/2025 03:21:44 - WARNING -   	 vision_patch_size: 32
04/28/2025 03:21:44 - WARNING -   	 context_length: 77
04/28/2025 03:21:44 - WARNING -   	 vocab_size: 49408
04/28/2025 03:21:44 - WARNING -   	 transformer_width: 512
04/28/2025 03:21:44 - WARNING -   	 transformer_heads: 8
04/28/2025 03:21:44 - WARNING -   	 transformer_layers: 12
04/28/2025 03:21:44 - WARNING -   		 linear_patch: 2d
04/28/2025 03:21:44 - WARNING -   	 cut_top_layer: 0
04/28/2025 03:21:46 - WARNING -   	 sim_header: seqTransf
04/28/2025 03:21:50 - INFO -   --------------------
04/28/2025 03:21:50 - INFO -   Weights from pretrained model not used in CLIP4Clip:
   clip.input_resolution
   clip.context_length
   clip.vocab_size
04/28/2025 03:21:52 - INFO -   ***** Running test *****
04/28/2025 03:21:52 - INFO -     Num examples = 1000
04/28/2025 03:21:52 - INFO -     Batch size = 8
04/28/2025 03:21:52 - INFO -     Num steps = 125
04/28/2025 03:21:52 - INFO -   ***** Running val *****
04/28/2025 03:21:52 - INFO -     Num examples = 1000
04/28/2025 03:21:56 - INFO -   ***** Running training *****
04/28/2025 03:21:56 - INFO -     Num examples = 18000
04/28/2025 03:21:56 - INFO -     Batch size = 64
04/28/2025 03:21:56 - INFO -     Num steps = 5620
Epoch 1:  35% 99/281 [08:39<18:48,  6.20s/it, loss=1.14] 04/28/2025 03:30:36 - INFO -   Epoch: 1/20, Step: 100/281, Lr: , Loss: 1.144521, Time/step: 5.200022
Epoch 1:  71% 199/281 [15:43<03:25,  2.50s/it, loss=1.27] 04/28/2025 03:37:40 - INFO -   Epoch: 1/20, Step: 200/281, Lr: , Loss: 1.274870, Time/step: 4.234502
Epoch 1: 100% 281/281 [21:15<00:00,  4.54s/it, loss=0.609]
04/28/2025 03:43:12 - INFO -   Epoch 1/20 Finished, Train Loss: 1.092548
04/28/2025 03:43:13 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.0
04/28/2025 03:43:13 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.0
Evaluating: 100% 125/125 [01:49<00:00,  1.14it/s]
04/28/2025 03:46:13 - INFO -   sim matrix size: 1000, 1000
04/28/2025 03:46:13 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 03:46:13 - INFO -   Text-to-Video:
04/28/2025 03:46:13 - INFO -   	>>>  R@1: 36.6 - R@5: 62.8 - R@10: 73.2 - Median R: 3.0 - Mean R: 21.8
04/28/2025 03:46:13 - INFO -   Video-to-Text:
04/28/2025 03:46:13 - INFO -   	>>>  V2T$R@1: 37.0 - V2T$R@5: 62.4 - V2T$R@10: 72.9 - V2T$Median R: 3.0 - V2T$Mean R: 20.4
04/28/2025 03:46:13 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.0, the R1 is: 36.6000
Epoch 2:   6% 18/281 [01:47<31:06,  7.10s/it, loss=0.612]04/28/2025 03:48:01 - INFO -   Epoch: 2/20, Step: 19/281, Lr: , Loss: 0.611577, Time/step: 1.079375
Epoch 2:  42% 118/281 [08:52<06:03,  2.23s/it, loss=0.869]04/28/2025 03:55:06 - INFO -   Epoch: 2/20, Step: 119/281, Lr: , Loss: 0.869314, Time/step: 4.248222
Epoch 2:  78% 218/281 [16:12<05:53,  5.62s/it, loss=1]    04/28/2025 04:02:26 - INFO -   Epoch: 2/20, Step: 219/281, Lr: , Loss: 1.002786, Time/step: 4.400389
Epoch 2: 100% 281/281 [20:18<00:00,  4.34s/it, loss=0.638]
04/28/2025 04:06:32 - INFO -   Epoch 2/20 Finished, Train Loss: 0.676165
04/28/2025 04:06:33 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.1
04/28/2025 04:06:33 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.1
Evaluating: 100% 125/125 [01:11<00:00,  1.74it/s]
04/28/2025 04:08:56 - INFO -   sim matrix size: 1000, 1000
04/28/2025 04:08:56 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 04:08:56 - INFO -   Text-to-Video:
04/28/2025 04:08:56 - INFO -   	>>>  R@1: 36.4 - R@5: 64.6 - R@10: 74.1 - Median R: 3.0 - Mean R: 20.5
04/28/2025 04:08:56 - INFO -   Video-to-Text:
04/28/2025 04:08:56 - INFO -   	>>>  V2T$R@1: 33.5 - V2T$R@5: 61.1 - V2T$R@10: 70.9 - V2T$Median R: 3.0 - V2T$Mean R: 21.9
04/28/2025 04:08:56 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.0, the R1 is: 36.6000
Epoch 3:  13% 37/281 [02:57<10:32,  2.59s/it, loss=0.599]04/28/2025 04:11:53 - INFO -   Epoch: 3/20, Step: 38/281, Lr: , Loss: 0.598498, Time/step: 1.776191
Epoch 3:  49% 137/281 [10:26<19:32,  8.14s/it, loss=0.335]04/28/2025 04:19:23 - INFO -   Epoch: 3/20, Step: 138/281, Lr: , Loss: 0.335173, Time/step: 4.491500
Epoch 3:  84% 237/281 [17:26<02:45,  3.77s/it, loss=0.342]04/28/2025 04:26:22 - INFO -   Epoch: 3/20, Step: 238/281, Lr: , Loss: 0.341742, Time/step: 4.198144
Epoch 3: 100% 281/281 [20:14<00:00,  4.32s/it, loss=0.517]
04/28/2025 04:29:11 - INFO -   Epoch 3/20 Finished, Train Loss: 0.490912
04/28/2025 04:29:12 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.2
04/28/2025 04:29:12 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.2
Evaluating: 100% 125/125 [01:12<00:00,  1.72it/s]
04/28/2025 04:31:36 - INFO -   sim matrix size: 1000, 1000
04/28/2025 04:31:36 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 04:31:36 - INFO -   Text-to-Video:
04/28/2025 04:31:36 - INFO -   	>>>  R@1: 37.3 - R@5: 63.3 - R@10: 74.2 - Median R: 3.0 - Mean R: 20.9
04/28/2025 04:31:36 - INFO -   Video-to-Text:
04/28/2025 04:31:36 - INFO -   	>>>  V2T$R@1: 34.8 - V2T$R@5: 59.2 - V2T$R@10: 72.7 - V2T$Median R: 3.0 - V2T$Mean R: 18.7
04/28/2025 04:31:36 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.2, the R1 is: 37.3000
Epoch 4:  20% 56/281 [04:26<07:14,  1.93s/it, loss=0.41] 04/28/2025 04:36:03 - INFO -   Epoch: 4/20, Step: 57/281, Lr: , Loss: 0.410001, Time/step: 2.669961
Epoch 4:  56% 156/281 [11:38<12:15,  5.88s/it, loss=0.256]04/28/2025 04:43:15 - INFO -   Epoch: 4/20, Step: 157/281, Lr: , Loss: 0.255464, Time/step: 4.316295
Epoch 4:  91% 256/281 [18:47<00:51,  2.06s/it, loss=0.345]04/28/2025 04:50:24 - INFO -   Epoch: 4/20, Step: 257/281, Lr: , Loss: 0.344610, Time/step: 4.289997
Epoch 4: 100% 281/281 [20:18<00:00,  4.34s/it, loss=0.491]
04/28/2025 04:51:55 - INFO -   Epoch 4/20 Finished, Train Loss: 0.341625
04/28/2025 04:51:56 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.3
04/28/2025 04:51:56 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.3
Evaluating: 100% 125/125 [01:12<00:00,  1.72it/s]
04/28/2025 04:54:19 - INFO -   sim matrix size: 1000, 1000
04/28/2025 04:54:19 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 04:54:19 - INFO -   Text-to-Video:
04/28/2025 04:54:19 - INFO -   	>>>  R@1: 37.3 - R@5: 64.1 - R@10: 74.8 - Median R: 3.0 - Mean R: 20.2
04/28/2025 04:54:19 - INFO -   Video-to-Text:
04/28/2025 04:54:19 - INFO -   	>>>  V2T$R@1: 34.1 - V2T$R@5: 57.3 - V2T$R@10: 70.9 - V2T$Median R: 4.0 - V2T$Mean R: 21.1
04/28/2025 04:54:19 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.3, the R1 is: 37.3000
Epoch 5:  27% 75/281 [05:42<16:41,  4.86s/it, loss=0.309]04/28/2025 05:00:02 - INFO -   Epoch: 5/20, Step: 76/281, Lr: , Loss: 0.309169, Time/step: 3.430822
Epoch 5:  62% 175/281 [12:48<03:48,  2.16s/it, loss=0.258]04/28/2025 05:07:08 - INFO -   Epoch: 5/20, Step: 176/281, Lr: , Loss: 0.258105, Time/step: 4.258496
Epoch 5:  98% 275/281 [20:09<00:21,  3.55s/it, loss=0.321]04/28/2025 05:14:29 - INFO -   Epoch: 5/20, Step: 276/281, Lr: , Loss: 0.320916, Time/step: 4.412040
Epoch 5: 100% 281/281 [20:19<00:00,  4.34s/it, loss=0.41]
04/28/2025 05:14:39 - INFO -   Epoch 5/20 Finished, Train Loss: 0.277226
04/28/2025 05:14:40 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.4
04/28/2025 05:14:40 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.4
Evaluating: 100% 125/125 [01:11<00:00,  1.74it/s]
04/28/2025 05:17:02 - INFO -   sim matrix size: 1000, 1000
04/28/2025 05:17:02 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 05:17:02 - INFO -   Text-to-Video:
04/28/2025 05:17:02 - INFO -   	>>>  R@1: 37.2 - R@5: 63.1 - R@10: 75.0 - Median R: 3.0 - Mean R: 22.3
04/28/2025 05:17:02 - INFO -   Video-to-Text:
04/28/2025 05:17:02 - INFO -   	>>>  V2T$R@1: 32.5 - V2T$R@5: 60.7 - V2T$R@10: 71.6 - V2T$Median R: 3.0 - V2T$Mean R: 20.7
04/28/2025 05:17:02 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.3, the R1 is: 37.3000
Epoch 6:  33% 94/281 [07:11<07:52,  2.53s/it, loss=0.227]04/28/2025 05:24:14 - INFO -   Epoch: 6/20, Step: 95/281, Lr: , Loss: 0.227034, Time/step: 4.318504
Epoch 6:  69% 194/281 [14:39<09:06,  6.28s/it, loss=0.165]04/28/2025 05:31:42 - INFO -   Epoch: 6/20, Step: 195/281, Lr: , Loss: 0.164870, Time/step: 4.481080
Epoch 6: 100% 281/281 [20:22<00:00,  4.35s/it, loss=0.183]
04/28/2025 05:37:25 - INFO -   Epoch 6/20 Finished, Train Loss: 0.228818
04/28/2025 05:37:26 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.5
04/28/2025 05:37:26 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.5
Evaluating: 100% 125/125 [01:10<00:00,  1.76it/s]
04/28/2025 05:39:47 - INFO -   sim matrix size: 1000, 1000
04/28/2025 05:39:47 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 05:39:47 - INFO -   Text-to-Video:
04/28/2025 05:39:47 - INFO -   	>>>  R@1: 36.8 - R@5: 63.5 - R@10: 74.9 - Median R: 3.0 - Mean R: 22.3
04/28/2025 05:39:47 - INFO -   Video-to-Text:
04/28/2025 05:39:47 - INFO -   	>>>  V2T$R@1: 32.3 - V2T$R@5: 58.6 - V2T$R@10: 70.3 - V2T$Median R: 3.0 - V2T$Mean R: 22.4
04/28/2025 05:39:47 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.3, the R1 is: 37.3000
Epoch 7:   5% 13/281 [01:11<13:49,  3.10s/it, loss=0.117]04/28/2025 05:40:59 - INFO -   Epoch: 7/20, Step: 14/281, Lr: , Loss: 0.117361, Time/step: 0.716434
Epoch 7:  40% 113/281 [08:37<22:34,  8.06s/it, loss=0.12] 04/28/2025 05:48:25 - INFO -   Epoch: 7/20, Step: 114/281, Lr: , Loss: 0.119809, Time/step: 4.460289
Epoch 7:  76% 213/281 [15:45<05:09,  4.55s/it, loss=0.347]04/28/2025 05:55:32 - INFO -   Epoch: 7/20, Step: 214/281, Lr: , Loss: 0.346669, Time/step: 4.278004
Epoch 7: 100% 281/281 [20:15<00:00,  4.32s/it, loss=0.159]
04/28/2025 06:00:02 - INFO -   Epoch 7/20 Finished, Train Loss: 0.196630
04/28/2025 06:00:04 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.6
04/28/2025 06:00:04 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.6
Evaluating: 100% 125/125 [01:10<00:00,  1.76it/s]
04/28/2025 06:02:26 - INFO -   sim matrix size: 1000, 1000
04/28/2025 06:02:26 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 06:02:26 - INFO -   Text-to-Video:
04/28/2025 06:02:26 - INFO -   	>>>  R@1: 37.3 - R@5: 62.7 - R@10: 74.2 - Median R: 3.0 - Mean R: 21.8
04/28/2025 06:02:26 - INFO -   Video-to-Text:
04/28/2025 06:02:26 - INFO -   	>>>  V2T$R@1: 33.4 - V2T$R@5: 58.9 - V2T$R@10: 71.4 - V2T$Median R: 3.0 - V2T$Mean R: 20.8
04/28/2025 06:02:26 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.6, the R1 is: 37.3000
Epoch 8:  11% 32/281 [03:00<06:11,  1.49s/it, loss=0.14] 04/28/2025 06:05:27 - INFO -   Epoch: 8/20, Step: 33/281, Lr: , Loss: 0.140017, Time/step: 1.811075
Epoch 8:  47% 132/281 [09:54<09:29,  3.82s/it, loss=0.264]04/28/2025 06:12:21 - INFO -   Epoch: 8/20, Step: 133/281, Lr: , Loss: 0.263715, Time/step: 4.131731
Epoch 8:  83% 232/281 [17:27<01:14,  1.52s/it, loss=0.136]04/28/2025 06:19:54 - INFO -   Epoch: 8/20, Step: 233/281, Lr: , Loss: 0.136013, Time/step: 4.536934
Epoch 8: 100% 281/281 [20:22<00:00,  4.35s/it, loss=0.311]
04/28/2025 06:22:49 - INFO -   Epoch 8/20 Finished, Train Loss: 0.182860
04/28/2025 06:22:50 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.7
04/28/2025 06:22:50 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.7
Evaluating: 100% 125/125 [01:12<00:00,  1.71it/s]
04/28/2025 06:25:18 - INFO -   sim matrix size: 1000, 1000
04/28/2025 06:25:18 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 06:25:18 - INFO -   Text-to-Video:
04/28/2025 06:25:18 - INFO -   	>>>  R@1: 38.0 - R@5: 63.9 - R@10: 74.6 - Median R: 2.0 - Mean R: 21.7
04/28/2025 06:25:18 - INFO -   Video-to-Text:
04/28/2025 06:25:18 - INFO -   	>>>  V2T$R@1: 33.7 - V2T$R@5: 61.4 - V2T$R@10: 71.5 - V2T$Median R: 3.0 - V2T$Mean R: 20.5
04/28/2025 06:25:18 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.7, the R1 is: 38.0000
Epoch 9:  18% 51/281 [04:13<22:48,  5.95s/it, loss=0.14]  04/28/2025 06:29:32 - INFO -   Epoch: 9/20, Step: 52/281, Lr: , Loss: 0.140293, Time/step: 2.539914
Epoch 9:  54% 151/281 [11:14<03:56,  1.82s/it, loss=0.135]04/28/2025 06:36:33 - INFO -   Epoch: 9/20, Step: 152/281, Lr: , Loss: 0.135248, Time/step: 4.210295
Epoch 9:  89% 251/281 [18:49<02:38,  5.28s/it, loss=0.161]04/28/2025 06:44:07 - INFO -   Epoch: 9/20, Step: 252/281, Lr: , Loss: 0.160834, Time/step: 4.542937
Epoch 9: 100% 281/281 [20:28<00:00,  4.37s/it, loss=0.208]
04/28/2025 06:45:47 - INFO -   Epoch 9/20 Finished, Train Loss: 0.163093
04/28/2025 06:45:48 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.8
04/28/2025 06:45:48 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.8
Evaluating: 100% 125/125 [01:12<00:00,  1.73it/s]
04/28/2025 06:48:13 - INFO -   sim matrix size: 1000, 1000
04/28/2025 06:48:13 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 06:48:13 - INFO -   Text-to-Video:
04/28/2025 06:48:13 - INFO -   	>>>  R@1: 39.1 - R@5: 64.2 - R@10: 75.0 - Median R: 2.0 - Mean R: 22.6
04/28/2025 06:48:13 - INFO -   Video-to-Text:
04/28/2025 06:48:13 - INFO -   	>>>  V2T$R@1: 34.6 - V2T$R@5: 61.8 - V2T$R@10: 72.9 - V2T$Median R: 3.0 - V2T$Mean R: 20.5
04/28/2025 06:48:13 - INFO -   The best model is: /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.8, the R1 is: 39.1000
Epoch 10:  25% 70/281 [05:24<10:03,  2.86s/it, loss=0.137] 04/28/2025 06:53:38 - INFO -   Epoch: 10/20, Step: 71/281, Lr: , Loss: 0.137206, Time/step: 3.248181
Epoch 10:  60% 170/281 [12:48<04:29,  2.43s/it, loss=0.0763]04/28/2025 07:01:02 - INFO -   Epoch: 10/20, Step: 171/281, Lr: , Loss: 0.076272, Time/step: 4.437935
Epoch 10:  96% 270/281 [20:02<00:44,  4.05s/it, loss=0.165]04/28/2025 07:08:16 - INFO -   Epoch: 10/20, Step: 271/281, Lr: , Loss: 0.164829, Time/step: 4.340184
Epoch 10: 100% 281/281 [20:24<00:00,  4.36s/it, loss=0.141]
04/28/2025 07:08:37 - INFO -   Epoch 10/20 Finished, Train Loss: 0.144718
04/28/2025 07:08:39 - INFO -   Model saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_model.bin.9
04/28/2025 07:08:39 - INFO -   Optimizer saved to /content/CLIP_video/ckpts/ckpt_msrvtt_retrieval_looseType/pytorch_opt.bin.9
Evaluating: 100% 125/125 [01:11<00:00,  1.76it/s]
04/28/2025 07:11:00 - INFO -   sim matrix size: 1000, 1000
04/28/2025 07:11:00 - INFO -   	 Length-T: 1000, Length-V:1000
04/28/2025 07:11:00 - INFO -   Text-to-Video:
04/28/2025 07:11:00 - INFO -   	>>>  R@1: 37.5 - R@5: 63.3 - R@10: 74.5 - Median R: 3.0 - Mean R: 22.0
04/28/2025 07:11:00 - INFO -   Video-to-Text:
04/28/2025 07:11:00 - INFO -   	>>>  V2T$R@1: 34.2 - V2T$R@5: 60.8 - V2T$R@10: 71.9 - V2T$Median R: 3.0 - V2T$Mean R: 20.9